name: MusicTrainer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip
  - certifi=2023.7.22
  - chardet=5.2.0
  - charset-normalizer=3.2.0
  - click=8.1.7
  - colorama=0.4.6
  - cycler=0.11.0
  - filelock=3.12.2
  - fonttools=4.38.0
  - fsspec=2023.1.0
  - idna=3.4
  - importlib-metadata=6.7.0
  - jellyfish=1.0.0
  - joblib=1.3.2
  - jsonpickle=3.0.2
  - kiwisolver=1.4.4
  - librosa=0.10.1
  - matplotlib=3.5.3
  - more-itertools=9.1.0
  - music21=7.3.3
  - nltk=3.8.1
  - packaging=23.1
  - pandas=1.3.5
  - pillow=9.5.0
  - pyparsing=3.1.1
  - python-dateutil=2.8.2
  - pytz=2023.3
  - pyyaml=6.0.1
  - regex=2023.8.8
  - requests=2.31.0
  - sacremoses=0.0.53
  - six=1.16.0
  - tqdm=4.66.1
  - typing-extensions=4.7.1
  - unidecode=1.3.6
  - urllib3=2.0.4
  - webcolors=1.13
  - zipp=3.15.0
  - transformers=4.18.0         # stay in conda since available
  - pip:
      - huggingface-hub==0.16.4   # move to pip
      - mido==1.3.0               # pip
      - tokenizers==0.12.1        # pip
